# <h1 style="color:#AED6F1 ; font-weight: bold; font-style: italic;">Loading Data</h1>

In [4]:
import soundscapy
import pandas as pd
df = pd.read_excel("Data-for-Plotting.xlsx", sheet_name="Tabelle1")
df

,LocationID,SessionID,GroupID,RecordID,Language,Lockdown,start_time,end_time,latitude,longitude,...,occ00_other,Occupation,edu00,eth00,eth00_other,misc00,misc03,misc03_other,misc04,misc01
0,CamdenTown,CamdenTown1,CT101,525.0,English,0,2019-05-02 11:40:00,2019-05-02 11:43:00,51.539124,-0.142624,...,NaN,Employed,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,CamdenTown,CamdenTown1,CT101,561.0,English,0,2019-05-02 11:40:00,2019-05-02 11:43:00,51.539124,-0.142624,...,NaN,Employed,2.0,1.0,NaN,NaN,2.0,NaN,NaN,NaN
2,CamdenTown,CamdenTown1,CT101,526.0,English,0,2019-05-02 11:41:00,2019-05-02 11:44:00,51.539124,-0.142624,...,NaN,Employed,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
3,CamdenTown,CamdenTown1,CT102,560.0,English,0,2019-05-02 11:50:00,2019-05-02 11:53:00,51.539124,-0.142624,...,NaN,Employed,5.0,1.0,NaN,NaN,2.0,NaN,NaN,NaN
4,CamdenTown,CamdenTown1,CT103,527.0,English,0,2019-05-02 11:49:00,2019-05-02 11:54:00,51.539124,-0.142624,...,NaN,Employed,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
5,CamdenTown,CamdenTown1,CT104,528.0,English,0,2019-05-02 11:52:00,2019-05-02 12:03:00,51.539124,-0.142624,...,NaN,Unemployed,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
6,CamdenTown,CamdenTown1,CT105,555.0,English,0,2019-05-02 11:56:00,2019-05-02 12:09:00,51.539124,-0.142624,...,NaN,Unemployed,5.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN
7,CamdenTown,CamdenTown1,CT105,529.0,English,0,2019-05-02 11:56:00,2019-05-02 12:09:00,51.539124,-0.142624,...,NaN,Unemployed,5.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
8,CamdenTown,CamdenTown1,CT106,530.0,English,0,2019-05-02 12:07:00,2019-05-02 12:12:00,51.539124,-0.142624,...,NaN,RatherNotSay,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
9,CamdenTown,CamdenTown1,CT107,559.0,English,0,2019-05-02 12:20:00,2019-05-02 12:25:00,51.539124,-0.142624,...,NaN,Retired,4.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN
10,EustonTap,EustonTap4,ET401,NaN,NaN,1,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,EustonTap,EustonTap4,ET402,NaN,NaN,1,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,EustonTap,EustonTap4,ET403,NaN,NaN,1,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,EustonTap,EustonTap4,ET404,NaN,NaN,1,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,EustonTap,EustonTap4,ET405,NaN,NaN,1,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,EustonTap,EustonTap4,ET406,NaN,NaN,1,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,EustonTap,EustonTap4,ET407,NaN,NaN,1,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,EustonTap,EustonTap4,ET408,NaN,NaN,1,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,EustonTap,EustonTap4,ET409,NaN,NaN,1,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,EustonTap,EustonTap4,ET410,NaN,NaN,1,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,TorringtonSq,TorringtonSq5,TS532,NaN,NaN,1,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,TorringtonSq,TorringtonSq5,TS533,NaN,NaN,1,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,TorringtonSq,TorringtonSq5,TS534,NaN,NaN,1,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,TorringtonSq,TorringtonSq5,TS535,NaN,NaN,1,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,TorringtonSq,TorringtonSq5,TS536,NaN,NaN,1,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,TorringtonSq,TorringtonSq5,TS537,NaN,NaN,1,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,TorringtonSq,TorringtonSq5,TS538,NaN,NaN,1,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,TorringtonSq,TorringtonSq5,TS539,NaN,NaN,1,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,TorringtonSq,TorringtonSq5,TS540,NaN,NaN,1,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,TorringtonSq,TorringtonSq5,TS541,NaN,NaN,1,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,TateModern,TateModern3,TM321,748.0,English,0,2019-05-24 12:10:00,2019-05-24 12:13:00,51.508484,-0.099861,...,NaN,Employed,5.0,1.0,NaN,NaN,2.0,NaN,1.0,NaN
31,TateModern,TateModern3,TM322,747.0,English,0,2019-05-24 12:09:00,2019-05-24 12:11:00,51.508493,-0.099921,...,NaN,Employed,7.0,1.0,NaN,NaN,2.0,NaN,3.0,NaN
32,TateModern,TateModern3,TM323,777.0,English,0,2019-05-24 12:18:00,2019-05-24 12:23:00,51.508444,-0.099866,...,NaN,Retired,3.0,1.0,NaN,NaN,3.0,school event,3.0,NaN
33,TateModern,TateModern3,TM324,773.0,English,0,2019-05-24 12:24:00,2019-05-24 12:39:00,51.508444,-0.099866,...,NaN,Employed,5.0,1.0,NaN,NaN,2.0,NaN,NaN,seagulls
34,TateModern,TateModern3,TM324,749.0,English,0,2019-05-24 12:20:00,2019-05-24 12:22:00,51.508483,-0.099884,...,NaN,Employed,5.0,1.0,NaN,NaN,1.0,NaN,3.0,NaN
35,TateModern,TateModern3,TM325,767.0,English,0,2019-05-24 12:30:00,2019-05-24 12:37:00,51.508444,-0.099866,...,NaN,Employed,4.0,1.0,NaN,NaN,2.0,NaN,3.0,NaN
36,TateModern,TateModern3,TM325,772.0,English,0,2019-05-24 12:30:00,2019-05-24 12:35:00,51.508444,-0.099866,...,NaN,RatherNotSay,4.0,1.0,NaN,NaN,2.0,NaN,3.0,NaN
37,TateModern,TateModern3,TM326,771.0,English,0,2019-05-24 17:43:00,2019-05-24 12:46:00,51.508444,-0.099866,...,NaN,Employed,7.0,7.0,latino,NaN,1.0,NaN,2.0,i believe sirens are a big problem
38,TateModern,TateModern3,TM327,751.0,English,0,2019-05-24 12:47:00,2019-05-24 12:51:00,51.508409,-0.099869,...,NaN,Student,2.0,1.0,NaN,NaN,2.0,NaN,1.0,NaN
39,TateModern,TateModern3,TM328,752.0,English,0,2019-05-24 12:50:00,2019-05-24 12:55:00,51.508531,-0.099814,...,NaN,Employed,5.0,5.0,NaN,NaN,1.0,NaN,3.0,NaN
40,RegentsParkFields,RegentsParkFields1,RF116,815.0,English,0,2019-05-31 12:22:00,2019-05-31 12:26:00,51.532535,-0.146275,...,NaN,Employed,5.0,1.0,NaN,NaN,1.0,NaN,3.0,NaN
41,RegentsParkFields,RegentsParkFields1,RF116,816.0,English,0,2019-05-31 12:24:00,2019-05-31 12:26:00,51.530675,-0.149612,...,NaN,Employed,6.0,1.0,NaN,NaN,1.0,NaN,3.0,NaN
42,RegentsParkFields,RegentsParkFields1,RF116,814.0,English,0,2019-05-31 11:22:00,2019-05-31 11:26:00,51.532535,-0.146275,...,NaN,Employed,5.0,1.0,NaN,NaN,1.0,NaN,3.0,NaN
43,RegentsParkFields,RegentsParkFields1,RF117,818.0,English,0,2019-05-31 11:26:00,2019-05-31 11:30:00,51.530492,-0.146047,...,NaN,Employed,1.0,1.0,NaN,NaN,2.0,NaN,3.0,NaN
44,RegentsParkFields,RegentsParkFields1,RF117,817.0,English,0,2019-05-31 11:27:00,2019-05-31 11:29:00,51.531420,-0.145995,...,NaN,Employed,5.0,1.0,NaN,NaN,2.0,NaN,3.0,NaN
45,RegentsParkFields,RegentsParkFields1,RF118,819.0,English,0,2019-05-31 11:32:00,2019-05-31 11:35:00,51.532535,-0.146275,...,NaN,Student,5.0,2.0,NaN,NaN,1.0,NaN,3.0,NaN
46,RegentsParkFields,RegentsParkFields1,RF119,820.0,English,0,2019-05-31 12:35:00,2019-05-31 12:38:00,51.530675,-0.149612,...,NaN,Other,5.0,1.0,NaN,NaN,2.0,NaN,1.0,Lots of helicopters today
47,RegentsParkFields,RegentsParkFields1,RF120,822.0,English,0,2019-05-31 12:28:00,2019-05-31 12:37:00,51.532252,-0.146210,...,NaN,Employed,5.0,1.0,NaN,NaN,2.0,NaN,3.0,NaN
48,RegentsParkFields,RegentsParkFields1,RF120,821.0,English,0,2019-05-31 11:28:00,2019-05-31 11:37:00,51.532535,-0.146275,...,NaN,Employed,7.0,1.0,NaN,NaN,2.0,NaN,3.0,NaN
49,RegentsParkFields,RegentsParkFields1,RF121,823.0,English,0,2019-05-31 11:38:00,2019-05-31 11:39:00,51.532535,-0.146275,...,NaN,Student,5.0,7.0,Hispanic,NaN,2.0,NaN,1.0,NaN
50,StPaulsRow,StPaulsRow1,SR101,957.0,English,0,2019-06-21 11:48:00,2019-06-21 11:49:00,51.514184,-0.099141,...,NaN,Student,3.0,1.0,NaN,NaN,2.0,NaN,1.0,NaN
51,StPaulsRow,StPaulsRow1,SR101,1098.0,English,0,2019-06-21 11:48:00,2019-06-21 11:52:00,51.514184,-0.099141,...,NaN,Student,3.0,1.0,NaN,NaN,2.0,NaN,NaN,Busy and bustling
52,StPaulsRow,StPaulsRow1,SR102,958.0,English,0,2019-06-21 11:48:00,2019-06-21 11:50:00,51.514247,-0.098938,...,NaN,Employed,5.0,1.0,NaN,NaN,2.0,NaN,1.0,NaN
53,StPaulsRow,StPaulsRow1,SR103,1097.0,English,0,2019-06-21 11:58:00,2019-06-21 12:01:00,51.514233,-0.099060,...,NaN,Student,1.0,3.0,NaN,NaN,2.0,NaN,NaN,NaN
54,StPaulsRow,StPaulsRow1,SR103,960.0,English,0,2019-06-21 11:55:00,2019-06-21 11:57:00,51.514233,-0.099060,...,NaN,Student,2.0,3.0,NaN,NaN,1.0,NaN,3.0,NaN
55,StPaulsRow,StPaulsRow1,SR104,1103.0,English,0,2019-06-21 12:56:00,2019-06-21 12:05:00,51.514179,-0.099025,...,NaN,Retired,5.0,1.0,NaN,NaN,3.0,"Knew the area well 69 years ago, it was very d...",NaN,NaN
56,StPaulsRow,StPaulsRow1,SR105,962.0,English,0,2019-06-21 11:59:00,2019-06-21 12:01:00,51.514179,-0.099025,...,NaN,Unemployed,5.0,3.0,NaN,NaN,1.0,NaN,1.0,NaN
57,StPaulsRow,StPaulsRow1,SR106,967.0,English,0,2019-06-21 12:05:00,2019-06-21 12:07:00,51.514235,-0.099017,...,NaN,Employed,NaN,1.0,NaN,NaN,1.0,NaN,3.0,NaN
58,StPaulsRow,StPaulsRow1,SR106,966.0,English,0,2019-06-21 12:05:00,2019-06-21 12:07:00,51.514218,-0.099037,...,NaN,Employed,4.0,1.0,NaN,NaN,1.0,NaN,3.0,No
59,StPaulsRow,StPaulsRow1,SR107,968.0,English,0,2019-06-21 12:06:00,2019-06-21 12:10:00,51.514187,-0.099013,...,NaN,Employed,7.0,3.0,NaN,NaN,2.0,NaN,1.0,NaN

# <h1 style="color:#AED6F1 ; font-weight: bold; font-style: italic;">Validating the Dataset</h1>

In [5]:
# 'df' will contain the validated DataFrame
# 'excl' will contain any excluded data or information returned by the method

df, excl = df.isd.validate_dataset()
df

Renaming PAQ columns.
Checking PAQ data quality.
Identified 20 samples to remove.
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]

,LocationID,SessionID,GroupID,RecordID,Language,Lockdown,start_time,end_time,latitude,longitude,...,occ00_other,Occupation,edu00,eth00,eth00_other,misc00,misc03,misc03_other,misc04,misc01
0,CamdenTown,CamdenTown1,CT101,525.0,English,0,2019-05-02 11:40:00,2019-05-02 11:43:00,51.539124,-0.142624,...,NaN,Employed,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,CamdenTown,CamdenTown1,CT101,561.0,English,0,2019-05-02 11:40:00,2019-05-02 11:43:00,51.539124,-0.142624,...,NaN,Employed,2.0,1.0,NaN,NaN,2.0,NaN,NaN,NaN
2,CamdenTown,CamdenTown1,CT101,526.0,English,0,2019-05-02 11:41:00,2019-05-02 11:44:00,51.539124,-0.142624,...,NaN,Employed,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
3,CamdenTown,CamdenTown1,CT102,560.0,English,0,2019-05-02 11:50:00,2019-05-02 11:53:00,51.539124,-0.142624,...,NaN,Employed,5.0,1.0,NaN,NaN,2.0,NaN,NaN,NaN
4,CamdenTown,CamdenTown1,CT103,527.0,English,0,2019-05-02 11:49:00,2019-05-02 11:54:00,51.539124,-0.142624,...,NaN,Employed,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
5,CamdenTown,CamdenTown1,CT104,528.0,English,0,2019-05-02 11:52:00,2019-05-02 12:03:00,51.539124,-0.142624,...,NaN,Unemployed,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
6,CamdenTown,CamdenTown1,CT105,555.0,English,0,2019-05-02 11:56:00,2019-05-02 12:09:00,51.539124,-0.142624,...,NaN,Unemployed,5.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN
7,CamdenTown,CamdenTown1,CT105,529.0,English,0,2019-05-02 11:56:00,2019-05-02 12:09:00,51.539124,-0.142624,...,NaN,Unemployed,5.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
8,CamdenTown,CamdenTown1,CT106,530.0,English,0,2019-05-02 12:07:00,2019-05-02 12:12:00,51.539124,-0.142624,...,NaN,RatherNotSay,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
9,CamdenTown,CamdenTown1,CT107,559.0,English,0,2019-05-02 12:20:00,2019-05-02 12:25:00,51.539124,-0.142624,...,NaN,Retired,4.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN
30,TateModern,TateModern3,TM321,748.0,English,0,2019-05-24 12:10:00,2019-05-24 12:13:00,51.508484,-0.099861,...,NaN,Employed,5.0,1.0,NaN,NaN,2.0,NaN,1.0,NaN
31,TateModern,TateModern3,TM322,747.0,English,0,2019-05-24 12:09:00,2019-05-24 12:11:00,51.508493,-0.099921,...,NaN,Employed,7.0,1.0,NaN,NaN,2.0,NaN,3.0,NaN
32,TateModern,TateModern3,TM323,777.0,English,0,2019-05-24 12:18:00,2019-05-24 12:23:00,51.508444,-0.099866,...,NaN,Retired,3.0,1.0,NaN,NaN,3.0,school event,3.0,NaN
33,TateModern,TateModern3,TM324,773.0,English,0,2019-05-24 12:24:00,2019-05-24 12:39:00,51.508444,-0.099866,...,NaN,Employed,5.0,1.0,NaN,NaN,2.0,NaN,NaN,seagulls
34,TateModern,TateModern3,TM324,749.0,English,0,2019-05-24 12:20:00,2019-05-24 12:22:00,51.508483,-0.099884,...,NaN,Employed,5.0,1.0,NaN,NaN,1.0,NaN,3.0,NaN
35,TateModern,TateModern3,TM325,767.0,English,0,2019-05-24 12:30:00,2019-05-24 12:37:00,51.508444,-0.099866,...,NaN,Employed,4.0,1.0,NaN,NaN,2.0,NaN,3.0,NaN
36,TateModern,TateModern3,TM325,772.0,English,0,2019-05-24 12:30:00,2019-05-24 12:35:00,51.508444,-0.099866,...,NaN,RatherNotSay,4.0,1.0,NaN,NaN,2.0,NaN,3.0,NaN
37,TateModern,TateModern3,TM326,771.0,English,0,2019-05-24 17:43:00,2019-05-24 12:46:00,51.508444,-0.099866,...,NaN,Employed,7.0,7.0,latino,NaN,1.0,NaN,2.0,i believe sirens are a big problem
38,TateModern,TateModern3,TM327,751.0,English,0,2019-05-24 12:47:00,2019-05-24 12:51:00,51.508409,-0.099869,...,NaN,Student,2.0,1.0,NaN,NaN,2.0,NaN,1.0,NaN
39,TateModern,TateModern3,TM328,752.0,English,0,2019-05-24 12:50:00,2019-05-24 12:55:00,51.508531,-0.099814,...,NaN,Employed,5.0,5.0,NaN,NaN,1.0,NaN,3.0,NaN
40,RegentsParkFields,RegentsParkFields1,RF116,815.0,English,0,2019-05-31 12:22:00,2019-05-31 12:26:00,51.532535,-0.146275,...,NaN,Employed,5.0,1.0,NaN,NaN,1.0,NaN,3.0,NaN
41,RegentsParkFields,RegentsParkFields1,RF116,816.0,English,0,2019-05-31 12:24:00,2019-05-31 12:26:00,51.530675,-0.149612,...,NaN,Employed,6.0,1.0,NaN,NaN,1.0,NaN,3.0,NaN
42,RegentsParkFields,RegentsParkFields1,RF116,814.0,English,0,2019-05-31 11:22:00,2019-05-31 11:26:00,51.532535,-0.146275,...,NaN,Employed,5.0,1.0,NaN,NaN,1.0,NaN,3.0,NaN
43,RegentsParkFields,RegentsParkFields1,RF117,818.0,English,0,2019-05-31 11:26:00,2019-05-31 11:30:00,51.530492,-0.146047,...,NaN,Employed,1.0,1.0,NaN,NaN,2.0,NaN,3.0,NaN
44,RegentsParkFields,RegentsParkFields1,RF117,817.0,English,0,2019-05-31 11:27:00,2019-05-31 11:29:00,51.531420,-0.145995,...,NaN,Employed,5.0,1.0,NaN,NaN,2.0,NaN,3.0,NaN
45,RegentsParkFields,RegentsParkFields1,RF118,819.0,English,0,2019-05-31 11:32:00,2019-05-31 11:35:00,51.532535,-0.146275,...,NaN,Student,5.0,2.0,NaN,NaN,1.0,NaN,3.0,NaN
46,RegentsParkFields,RegentsParkFields1,RF119,820.0,English,0,2019-05-31 12:35:00,2019-05-31 12:38:00,51.530675,-0.149612,...,NaN,Other,5.0,1.0,NaN,NaN,2.0,NaN,1.0,Lots of helicopters today
47,RegentsParkFields,RegentsParkFields1,RF120,822.0,English,0,2019-05-31 12:28:00,2019-05-31 12:37:00,51.532252,-0.146210,...,NaN,Employed,5.0,1.0,NaN,NaN,2.0,NaN,3.0,NaN
48,RegentsParkFields,RegentsParkFields1,RF120,821.0,English,0,2019-05-31 11:28:00,2019-05-31 11:37:00,51.532535,-0.146275,...,NaN,Employed,7.0,1.0,NaN,NaN,2.0,NaN,3.0,NaN
49,RegentsParkFields,RegentsParkFields1,RF121,823.0,English,0,2019-05-31 11:38:00,2019-05-31 11:39:00,51.532535,-0.146275,...,NaN,Student,5.0,7.0,Hispanic,NaN,2.0,NaN,1.0,NaN
50,StPaulsRow,StPaulsRow1,SR101,957.0,English,0,2019-06-21 11:48:00,2019-06-21 11:49:00,51.514184,-0.099141,...,NaN,Student,3.0,1.0,NaN,NaN,2.0,NaN,1.0,NaN
51,StPaulsRow,StPaulsRow1,SR101,1098.0,English,0,2019-06-21 11:48:00,2019-06-21 11:52:00,51.514184,-0.099141,...,NaN,Student,3.0,1.0,NaN,NaN,2.0,NaN,NaN,Busy and bustling
52,StPaulsRow,StPaulsRow1,SR102,958.0,English,0,2019-06-21 11:48:00,2019-06-21 11:50:00,51.514247,-0.098938,...,NaN,Employed,5.0,1.0,NaN,NaN,2.0,NaN,1.0,NaN
53,StPaulsRow,StPaulsRow1,SR103,1097.0,English,0,2019-06-21 11:58:00,2019-06-21 12:01:00,51.514233,-0.099060,...,NaN,Student,1.0,3.0,NaN,NaN,2.0,NaN,NaN,NaN
54,StPaulsRow,StPaulsRow1,SR103,960.0,English,0,2019-06-21 11:55:00,2019-06-21 11:57:00,51.514233,-0.099060,...,NaN,Student,2.0,3.0,NaN,NaN,1.0,NaN,3.0,NaN
55,StPaulsRow,StPaulsRow1,SR104,1103.0,English,0,2019-06-21 12:56:00,2019-06-21 12:05:00,51.514179,-0.099025,...,NaN,Retired,5.0,1.0,NaN,NaN,3.0,"Knew the area well 69 years ago, it was very d...",NaN,NaN
56,StPaulsRow,StPaulsRow1,SR105,962.0,English,0,2019-06-21 11:59:00,2019-06-21 12:01:00,51.514179,-0.099025,...,NaN,Unemployed,5.0,3.0,NaN,NaN,1.0,NaN,1.0,NaN
57,StPaulsRow,StPaulsRow1,SR106,967.0,English,0,2019-06-21 12:05:00,2019-06-21 12:07:00,51.514235,-0.099017,...,NaN,Employed,NaN,1.0,NaN,NaN,1.0,NaN,3.0,NaN
58,StPaulsRow,StPaulsRow1,SR106,966.0,English,0,2019-06-21 12:05:00,2019-06-21 12:07:00,51.514218,-0.099037,...,NaN,Employed,4.0,1.0,NaN,NaN,1.0,NaN,3.0,No
59,StPaulsRow,StPaulsRow1,SR107,968.0,English,0,2019-06-21 12:06:00,2019-06-21 12:10:00,51.514187,-0.099013,...,NaN,Employed,7.0,3.0,NaN,NaN,2.0,NaN,1.0,NaN

# <h1 style="color:#AED6F1 ; font-weight: bold; font-style: italic;">Calculating the ISOPleasant and ISOEventful Coordinate Values</h1>

In [7]:
paqs = df.sspy.return_paqs()
paqs

,RecordID,GroupID,SessionID,LocationID,PAQ1,PAQ2,PAQ3,PAQ4,PAQ5,PAQ6,PAQ7,PAQ8
0,525.0,CT101,CamdenTown1,CamdenTown,2.0,3.0,4.0,4.0,2.0,3.0,2.0,1.0
1,561.0,CT101,CamdenTown1,CamdenTown,3.0,2.0,2.0,4.0,4.0,4.0,1.0,1.0
2,526.0,CT101,CamdenTown1,CamdenTown,4.0,3.0,3.0,3.0,4.0,2.0,2.0,2.0
3,560.0,CT102,CamdenTown1,CamdenTown,4.0,2.0,2.0,2.0,3.0,5.0,5.0,5.0
4,527.0,CT103,CamdenTown1,CamdenTown,3.0,5.0,4.0,4.0,2.0,1.0,1.0,2.0
5,528.0,CT104,CamdenTown1,CamdenTown,2.0,5.0,4.0,4.0,2.0,2.0,1.0,2.0
6,555.0,CT105,CamdenTown1,CamdenTown,3.0,3.0,2.0,1.0,3.0,2.0,5.0,5.0
7,529.0,CT105,CamdenTown1,CamdenTown,4.0,4.0,4.0,5.0,3.0,3.0,2.0,2.0
8,530.0,CT106,CamdenTown1,CamdenTown,2.0,4.0,2.0,4.0,4.0,2.0,4.0,2.0
9,559.0,CT107,CamdenTown1,CamdenTown,4.0,4.0,3.0,4.0,4.0,1.0,3.0,2.0
30,748.0,TM321,TateModern3,TateModern,5.0,3.0,4.0,2.0,2.0,2.0,2.0,5.0
31,747.0,TM322,TateModern3,TateModern,4.0,4.0,4.0,2.0,2.0,1.0,2.0,4.0
32,777.0,TM323,TateModern3,TateModern,5.0,5.0,5.0,1.0,1.0,1.0,1.0,5.0
33,773.0,TM324,TateModern3,TateModern,5.0,4.0,2.0,2.0,1.0,1.0,4.0,4.0
34,749.0,TM324,TateModern3,TateModern,4.0,5.0,4.0,4.0,2.0,2.0,1.0,2.0
35,767.0,TM325,TateModern3,TateModern,4.0,5.0,3.0,4.0,3.0,1.0,1.0,2.0
36,772.0,TM325,TateModern3,TateModern,4.0,4.0,4.0,4.0,2.0,1.0,1.0,4.0
37,771.0,TM326,TateModern3,TateModern,4.0,4.0,4.0,3.0,4.0,2.0,2.0,2.0
38,751.0,TM327,TateModern3,TateModern,4.0,2.0,4.0,4.0,1.0,2.0,3.0,4.0
39,752.0,TM328,TateModern3,TateModern,4.0,4.0,5.0,2.0,2.0,3.0,3.0,3.0
40,815.0,RF116,RegentsParkFields1,RegentsParkFields,3.0,3.0,3.0,2.0,3.0,3.0,2.0,4.0
41,816.0,RF116,RegentsParkFields1,RegentsParkFields,1.0,1.0,5.0,5.0,5.0,5.0,1.0,1.0
42,814.0,RF116,RegentsParkFields1,RegentsParkFields,1.0,4.0,3.0,5.0,5.0,2.0,3.0,2.0
43,818.0,RF117,RegentsParkFields1,RegentsParkFields,5.0,5.0,2.0,1.0,1.0,1.0,2.0,5.0
44,817.0,RF117,RegentsParkFields1,RegentsParkFields,5.0,3.0,1.0,1.0,1.0,1.0,5.0,5.0
45,819.0,RF118,RegentsParkFields1,RegentsParkFields,4.0,1.0,2.0,2.0,2.0,1.0,2.0,5.0
46,820.0,RF119,RegentsParkFields1,RegentsParkFields,4.0,3.0,2.0,1.0,1.0,3.0,3.0,4.0
47,822.0,RF120,RegentsParkFields1,RegentsParkFields,4.0,4.0,2.0,1.0,1.0,2.0,4.0,5.0
48,821.0,RF120,RegentsParkFields1,RegentsParkFields,4.0,4.0,4.0,3.0,3.0,3.0,3.0,3.0
49,823.0,RF121,RegentsParkFields1,RegentsParkFields,5.0,3.0,2.0,1.0,1.0,1.0,3.0,5.0
50,957.0,SR101,StPaulsRow1,StPaulsRow,3.0,2.0,2.0,4.0,1.0,4.0,2.0,4.0
51,1098.0,SR101,StPaulsRow1,StPaulsRow,2.0,5.0,2.0,4.0,4.0,4.0,5.0,1.0
52,958.0,SR102,StPaulsRow1,StPaulsRow,4.0,3.0,3.0,2.0,1.0,2.0,3.0,4.0
53,1097.0,SR103,StPaulsRow1,StPaulsRow,5.0,4.0,5.0,4.0,1.0,3.0,2.0,5.0
54,960.0,SR103,StPaulsRow1,StPaulsRow,4.0,4.0,3.0,1.0,1.0,2.0,4.0,4.0
55,1103.0,SR104,StPaulsRow1,StPaulsRow,5.0,4.0,1.0,4.0,1.0,5.0,1.0,4.0
56,962.0,SR105,StPaulsRow1,StPaulsRow,4.0,3.0,4.0,2.0,2.0,3.0,2.0,3.0
57,967.0,SR106,StPaulsRow1,StPaulsRow,4.0,4.0,4.0,2.0,3.0,2.0,1.0,2.0
58,966.0,SR106,StPaulsRow1,StPaulsRow,4.0,4.0,3.0,4.0,3.0,4.0,4.0,4.0
59,968.0,SR107,StPaulsRow1,StPaulsRow,2.0,3.0,3.0,2.0,3.0,2.0,3.0,1.0